# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build

on:
  push:
    tags:
      - '*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build
        run: |
          make build
      - uses: actions/upload-artifact@v2
        with:
          name: metagen
          path: |
            bin/linux/metagen
