# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
      - name: Make (default)
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: metagen
          path: |
            build/src/metagen

  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
      - name: Make (all)
        run: make all
      - uses: actions/upload-artifact@v2
        with:
          name: metagen
          path: |
            build-linux/src/metagen
            build-macos/src/metagen
            build-windows/src/metagen.exe
